name: Build DEB/RPM and publish release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build DEB and RPM
        run: |
          sudo bash build.sh rpm deb

      - name: Create / Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: fonts
          name: "msttcore-fonts packages"
          draft: false
          prerelease: false
          files: |
            dist/debbuild/ttf-mscorefonts-installer_*.deb
            dist/rpmbuild/RPMS/noarch/msttcore-fonts-installer-*.noarch.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

